# Generated by Django 2.2.9 on 2020-01-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('1', '男'), ('2', '女')], default='1', max_length=1, verbose_name='性别')),
                ('age', models.PositiveIntegerField(verbose_name='年龄')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='登陆名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
