# Generated by Django 2.2.9 on 2020-01-19 17:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_auto_20200119_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-reorder']},
        ),
        migrations.AlterField(
            model_name='classify',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('681d53ad-8291-47f5-b8c5-d75542e0e15e'), editable=False, verbose_name='分类ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('f2534b51-025a-4bca-9400-53f049fff786'), editable=False, verbose_name='商品id'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('07353076-aa38-42bc-ba13-8a765b7fc599'), editable=False, verbose_name='分类ID'),
        ),
    ]
