# Generated by Django 2.2.9 on 2020-01-20 10:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_auto_20200119_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classify',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mall.Classify', verbose_name='商品分类自关联'),
        ),
        migrations.AlterField(
            model_name='classify',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='分类ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('06a67a25-da49-4f7d-967e-311574563587'), editable=False, verbose_name='商品id'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('fbdce7ec-3e24-4d82-8abe-68f5a5b390a5'), editable=False, verbose_name='分类ID'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
