# Generated by Django 2.2.9 on 2020-01-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_auto_20200110_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(related_name='student_to_course', to='mall.Course', verbose_name='选课'),
        ),
    ]
