# Generated by Django 2.2.9 on 2020-01-25 17:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_auto_20200120_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e39ec847-f6ea-4629-a145-1bc020288a53'), editable=False, verbose_name='商品id'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('a0845784-3bca-41f3-80e8-ff3d6d08571b'), editable=False, verbose_name='分类ID'),
        ),
    ]
