# Generated by Django 2.2.9 on 2020-01-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0005_collections_product_store_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='collections',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentaddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='student',
        ),
        migrations.DeleteModel(
            name='Collections',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentAddress',
        ),
        migrations.DeleteModel(
            name='StudentDetail',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
