# Generated by Django 2.2.9 on 2020-02-03 14:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0005_auto_20200125_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('c7d5518e-bcf5-49c1-98c6-ac8ccb569517'), editable=False, verbose_name='商品id'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('1d4694e7-48d1-463e-8d06-43e00a0719b0'), editable=False, verbose_name='分类ID'),
        ),
    ]
