# Generated by Django 2.2.9 on 2020-02-05 03:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0006_auto_20200203_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ramain_count',
            field=models.IntegerField(default=0, verbose_name='剩余库存'),
        ),
        migrations.AddField(
            model_name='product',
            name='score',
            field=models.FloatField(default=10.0, verbose_name='商品的评分'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku_count',
            field=models.IntegerField(default=0, verbose_name='库存'),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='浏览次数'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='%Y%m/product', verbose_name='主图'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('daab0895-e97d-4eb2-ba96-b6140fcb21b7'), editable=False, verbose_name='商品id'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('36f3fe15-da86-4c86-b116-4cf12c729525'), editable=False, verbose_name='分类ID'),
        ),
    ]
