# Generated by Django 2.2.9 on 2020-02-07 17:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0007_auto_20200205_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('4d10eafa-4826-4079-8af9-af211a9d84a7'), editable=False, verbose_name='商品id'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('7161ab95-328a-4709-b53e-1a5a172e1232'), editable=False, verbose_name='分类ID'),
        ),
    ]
