# Generated by Django 2.2.9 on 2020-02-10 12:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0009_auto_20200208_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classify',
            options={'ordering': ['-reorder'], 'verbose_name': '商品分类', 'verbose_name_plural': '商品分类'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-reorder'], 'verbose_name': '商品信息', 'verbose_name_plural': '商品信息'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '商品标签', 'verbose_name_plural': '商品标签'},
        ),
        migrations.AlterField(
            model_name='product',
            name='classes',
            field=models.ManyToManyField(blank=True, null=True, related_name='classes', to='mall.Classify', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('16b0248c-fec9-4193-9ea6-19f70a92244f'), editable=False, verbose_name='商品id'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='img',
            field=models.ImageField(upload_to='tag', verbose_name='标签主图'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('81614a4d-b0ad-4b8a-bc71-24d5da93a7d1'), editable=False, verbose_name='标签ID'),
        ),
    ]
