# Generated by Django 2.2.9 on 2020-02-10 12:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0010_auto_20200210_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classify',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mall.Classify', verbose_name='商品分类自关联'),
        ),
        migrations.AlterField(
            model_name='product',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='classes', to='mall.Classify', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('590858bb-3754-4007-a00d-3251ad86d9bf'), editable=False, verbose_name='商品id'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='img',
            field=models.ImageField(upload_to='classify', verbose_name='标签主图'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('d8191225-394e-402a-9519-9e5ccb2d8916'), editable=False, verbose_name='标签ID'),
        ),
    ]
