# Generated by Django 2.2.9 on 2020-01-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar', verbose_name='用户头像')),
                ('integral', models.IntegerField(default=0, verbose_name='用户积分')),
                ('nickname', models.CharField(max_length=32, verbose_name='昵称')),
                ('level', models.SmallIntegerField(default=1, verbose_name='用户级别')),
            ],
            options={
                'db_table': 'accounts_user',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('real_name', models.CharField(max_length=32, verbose_name='真实姓名')),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (0, '女')], default=1, verbose_name='性别')),
                ('age', models.SmallIntegerField(default=0, verbose_name='年龄')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='电子邮箱')),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号码')),
                ('is_email_valid', models.BooleanField(default=False, verbose_name='邮箱是否验证')),
                ('is_phone_valid', models.BooleanField(default=False, verbose_name='手机是否验证')),
                ('user', models.OneToOneField(on_delete=True, to='accounts.User', verbose_name='关联用户')),
            ],
            options={
                'db_table': 'accounts_user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('province', models.CharField(max_length=32, verbose_name='省份')),
                ('city', models.CharField(max_length=32, verbose_name='城市')),
                ('area', models.CharField(max_length=32, verbose_name='区域')),
                ('town', models.CharField(blank=True, max_length=32, null=True, verbose_name='街道')),
                ('address', models.CharField(max_length=64, verbose_name='详细地址')),
                ('username', models.CharField(max_length=32, verbose_name='收件人')),
                ('phone', models.CharField(max_length=32, verbose_name='收件人电话')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认地址')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('user', models.ForeignKey(on_delete=True, related_name='user_address', to='accounts.User', verbose_name='关联用户')),
            ],
            options={
                'db_table': 'accounts_user_address',
                'ordering': ['is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32, verbose_name='IP')),
                ('address', models.CharField(blank=True, max_length=32, null=True, verbose_name='地址')),
                ('source', models.CharField(max_length=32, verbose_name='登陆的来源')),
                ('oldpwd', models.CharField(max_length=256, verbose_name='旧密码')),
                ('newpwd', models.CharField(max_length=256, verbose_name='新密码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='密码修改时间')),
                ('user', models.ForeignKey(on_delete=True, related_name='user_password_log', to='accounts.User', verbose_name='关联用户')),
            ],
            options={
                'db_table': 'accounts_password_change_log',
            },
        ),
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='登陆的账号')),
                ('ip', models.CharField(max_length=32, verbose_name='IP')),
                ('address', models.CharField(blank=True, max_length=32, null=True, verbose_name='地址')),
                ('source', models.CharField(max_length=32, verbose_name='登陆的来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登陆时间')),
                ('user', models.ForeignKey(on_delete=True, related_name='user_login_record', to='accounts.User', verbose_name='关联用户')),
            ],
            options={
                'db_table': 'accounts_login_record',
            },
        ),
    ]
