# Generated by Django 2.2.9 on 2020-02-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200203_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_valid',
            field=models.BooleanField(default=1, verbose_name='是否有效'),
        ),
    ]
